let allPosts=[];
const listView=document.getElementById('post-list'),contentView=document.getElementById('post-content'),itemsContainer=document.getElementById('post-items'),filterContainer=document.getElementById('category-filter'),bodyContainer=document.getElementById('post-body'),commentsContainer=document.getElementById('comments-container'),backBtn=document.getElementById('back-btn');

fetch('posts/posts.json').then(response=>{if(!response.ok)throw new Error('文章列表加载失败');return response.json()}).then(posts=>{allPosts=posts;renderCategories();renderPosts(posts);const file=new URLSearchParams(location.search).get('post');if(file)loadPost(file)}).catch(error=>showStatus(itemsContainer,`⚠ ${error.message}`));

function showStatus(container,message){container.replaceChildren();const node=document.createElement('p');node.className='status-message';node.textContent=message;container.appendChild(node)}

function renderCategories(){filterContainer.replaceChildren();const categories=['全部',...new Set(allPosts.flatMap(post=>post.categories||[]))];categories.forEach((category,index)=>{const button=document.createElement('button');button.className=`category-tag${index===0?' active':''}`;button.type='button';button.textContent=category;button.setAttribute('aria-pressed',String(index===0));button.addEventListener('click',()=>{filterContainer.querySelectorAll('button').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});renderPosts(category==='全部'?allPosts:allPosts.filter(post=>post.categories.includes(category)))});filterContainer.appendChild(button)})}

function renderPosts(posts){itemsContainer.replaceChildren();if(!posts.length)return showStatus(itemsContainer,'该分类下暂无文章。');posts.forEach(post=>{const article=document.createElement('article'),meta=document.createElement('div'),heading=document.createElement('h3'),link=document.createElement('a'),summary=document.createElement('p');article.className='post-item';meta.className='post-meta';meta.textContent=post.date;(post.categories||[]).forEach(category=>{const tag=document.createElement('span');tag.className='tag';tag.textContent=category;meta.append(' ',tag)});link.href=`?post=${encodeURIComponent(post.file)}`;link.textContent=post.title;heading.appendChild(link);summary.className='post-summary';summary.textContent=post.summary;article.append(meta,heading,summary);itemsContainer.appendChild(article)})}

function loadPost(file){if(!/^posts\/[\w.-]+\.md$/.test(file))return showStatus(itemsContainer,'文章地址无效。');listView.classList.add('hidden');contentView.classList.add('active');scrollTo(0,0);showStatus(bodyContainer,'正在读取文章…');fetch(file).then(response=>{if(!response.ok)throw new Error('文章加载失败');return response.text()}).then(markdown=>{const title=markdown.split('\n')[0].replace(/^#\s*/,'');const rendered=marked.parse(markdown);bodyContainer.innerHTML=window.DOMPurify?DOMPurify.sanitize(rendered):rendered;document.title=`${title} · 刘靖臣`;loadComments()}).catch(error=>showStatus(bodyContainer,`⚠ ${error.message}`))}

function showListView(){contentView.classList.remove('active');listView.classList.remove('hidden');history.pushState({},'', './');document.title='博客 · 刘靖臣';commentsContainer.replaceChildren()}
backBtn.addEventListener('click',event=>{event.preventDefault();showListView()});
addEventListener('popstate',()=>{const file=new URLSearchParams(location.search).get('post');if(file)loadPost(file);else showListView()});

function loadComments(){commentsContainer.replaceChildren();const script=document.createElement('script');script.src='https://utteranc.es/client.js';script.setAttribute('repo','ljingchen77-rgb/learner');script.setAttribute('issue-term','pathname');script.setAttribute('theme',document.body.classList.contains('dark-mode')?'github-dark':'github-light');script.setAttribute('crossorigin','anonymous');script.async=true;commentsContainer.appendChild(script)}
